### ISSUE TITLE
船にサメが衝突（攻撃）した際に効果音を鳴らす。

### ISSUE THREAD

**Issue by OtObOx** [work-room-umi/ld50-maingame#114]
以下の効果音を船にサメが衝突（攻撃）した際に再生してください。

インゲーム効果音
SEイベント名|パラメーター|内容|詳細|
| ------------- | ------------- |------------- |------------- |
attack||サメが船の衝突した際の音|

宜しくお願い致します。

**Comment by koiusa** [comment]
コライダー仮置きですが、Prefab追加しました。
Assets/Project/Prefabs/BGMs/Shark/SharkSound.prefab

**Comment by koiusa** [comment]
実装は完了済みでクローズ
#170　でエラー確認
