### ISSUE TITLE
船に吸着した漂着物の耐久値が0になった際に効果音を再生する

### ISSUE THREAD

**Issue by OtObOx** [work-room-umi/ld50-maingame#115]
以下の効果音を船に吸着した漂着物の耐久値が0（漂着物が欠落した）際に再生してください。

インゲーム効果音
SEイベント名|パラメーター|内容|詳細|
| ------------- | ------------- |------------- |------------- |
break||漂流物の耐久値が無くなり欠落した際の音|

宜しくお願い致します。

**Comment by koiusa** [comment]
以下にPrefabを追加
Assets/Project/Prefabs/BGMs/PlayerShip/PlayerShipSound.prefab

**Comment by koiusa** [comment]
PlayerShipのActionから呼び出す処理で実装完了
クローズします
