### ISSUE TITLE
波しぶきのＳＥ用に船の速度変化を取得したい

### ISSUE THREAD

**Issue by koiusa** [work-room-umi/ld50-maingame#121]
現在の船の速度を以下の値で取得するプロパティをPlayerShipかPlayerShipLocomoterに付けてほしいのですが、可能でしょうか？
停止0
最大1

**Comment by tanitta** [comment]
かしこまりました。PlayerShipLocomoterにCurrentSpeedRate生やしておきますね。

**Comment by koiusa** [comment]
実装は完了しているのでクローズします
