### ISSUE TITLE
シーンへのSoundPrefabの追加

### ISSUE THREAD

**Issue by koiusa** [work-room-umi/ld50-maingame#126]
ループ系SEが一応動くようになったのでシーンへのSoundPrefabを追加して確認お願いします
問題なければコミットもお願いします

**Comment by koiusa** [comment]
![スクリーンショット 2022-04-04 012608](https://user-images.githubusercontent.com/71818379/161438160-1d68439f-c448-45d4-86b7-9ce46fd63504.png)

**Comment by koiusa** [comment]
Project/Prefabs/BGMs配下に配置しています

**Comment by koiusa** [comment]
BGM再生用Prefabは以下になります
タイミングの良いところでシーンへの配置をお願いします

全画面で使用想定の環境BGM
Assets/Project/Prefabs/BGMs/WaveSound.prefab

ゲームメインBGM（PlayerShipのInspector参照が必要）
Assets/Project/Prefabs/BGMs/PlayngSound.prefab

リザルトBGM
Assets/Project/Prefabs/BGMs/ResultSound.prefab

クレジット、エンディングBGM
Assets/Project/Prefabs/BGMs/CreditSound.prefab

**Comment by nim9** [comment]
やりますー

**Comment by YoshinoAlice2** [comment]
・Title
・Result
・Credit
のBGMはSceneに追加しました。

**Comment by koiusa** [comment]
ご協力ありがとうございました
