### ISSUE TITLE
船のマストの表示を切り替える

### ISSUE THREAD

**Issue by tanitta** [work-room-umi/ld50-maingame#134]
船体についてるパーツ（体力）の数によってマストの表示を切り替えます。

**Comment by tanitta** [comment]
PlayerShip Componentができたら実装開始。 #37

**Comment by tanitta** [comment]
一旦視認性のために船のマストは若干残したまま表示します。

**Comment by tanitta** [comment]
Assets/Project/Prefabs/Ship/Materials/Ship_Sail_LOD0.matのマテリアルのDissolveの値を0.12に変更してもらえると嬉しいです

**Comment by YoshinoAlice2** [comment]
変更されているのをかくにんしたので、プルリクをマージして、issueはクローズします！
