### ISSUE TITLE
岩など障害物にあたった時の効果音要りそうです

### ISSUE THREAD

**Issue by koiusa** [work-room-umi/ld50-maingame#135]
サメと併用でしょうか？

**Comment by OtObOx** [comment]
@tanitta サメの衝突と岩などの障害物との接触では何か異なるプレイヤーへの影響はありますでしょうか。
障害物と当たった場合はダメージが大きいなどありましたら教えて頂きたいです！

**Comment by OtObOx** [comment]
障害物と衝突した際の効果音はサメの攻撃音と併用になります。

**Comment by koiusa** [comment]
現状障害物と敵の効果音は同一のものを使用しています
問題ないのでクローズします
