### ISSUE TITLE
各種イベント用エフェクトの作成

### ISSUE THREAD

**Issue by noriben327** [work-room-umi/ld50-maingame#139]
フォルダの場所はここ
Project/Prefabs/Effects/

- [x] 1. 障害物にぶかったとき
EventEffects/HitRock.prefab
岩
白よりのグレー

- [x] 2. 敵キャラに攻撃されたとき
EventEffects/Break.prefab
船全体からポップコーンが出るような。
黒 紫

- [x] 3. アイテムを拾ったとき
EventEffects/DIY.prefab
木材拾ったときなど
とんかんとんかんDIYイメージの煙。

- [x] 持続ダメージで壊れたとき
詳細未定

・4. 船のなみしぶき
BoatSplash/BoatSplash.prefab

音が一瞬なので短いエフェクトにする。
アウトラインなしにする。

**Comment by noriben327** [comment]
まるっこい煙（岩とかにぶつかったとき）

![image](https://user-images.githubusercontent.com/40428780/161448858-3d1e89ad-d944-4404-98b1-b3e8e7d73d26.png)

**Comment by noriben327** [comment]
壊れた時。
黒い煙。
燃えてるわけじゃないけど破壊表現としてのオレンジ。

![image](https://user-images.githubusercontent.com/40428780/161452524-1442e1d7-f743-4b96-8a0d-e144dbba1215.png)

**Comment by noriben327** [comment]
アウトラインなし
![image](https://user-images.githubusercontent.com/40428780/161471853-de3e8bf3-96a5-4e1f-baab-833be385e8ab.png)

**Comment by YoshinoAlice2** [comment]
持続ダメージで壊れたときのエフェクトは詳細が決まりきらないのでオミットします！
