### ISSUE TITLE
カメラ制御のコンポーネント開発

### ISSUE THREAD

**Issue by HarukaKajita** [work-room-umi/ld50-maingame#15]
マウス操作でカメラの向きを変える感じ。
船体を見たい
周囲も見たい
ので、ピボットの位置とか柔軟にしたい。
でも、いい感じになりそうになかったら相談。

スムージングかけた方が良いかも。
Cinemachinで出来たら実装楽かも知れない。

**Comment by tanitta** [comment]
サメが近づいたらカメラがちょっと見下ろす形になってほしい。
