### ISSUE TITLE
波による常時ダメージ実装

### ISSUE THREAD

**Issue by HarukaKajita** [work-room-umi/ld50-maingame#151]
Wavesクラスで定期的にPlayerShipにダメージを与える機能追加。

- [x] Wavesコンポーネントが付いてるオブジェクトにAttackコンポーネントも付ける。
- [x] シーンからPlayerShipをFindしておく。
- [x] playerShip.AddDamage(this)を実行してダメージを与える。
- [x] 適当に攻撃間隔のインターバルとかレベルデザインに使えそうなパラメータがあったらpublicにしておいてほしい。
- [x] AttackのattackableCountはインスペクタから馬鹿でかい値にする。

レベルデザイン的に重要な機能になるかもしれないので何卒お願いします...! :pray:

**Comment by TrsNium** [comment]
https://github.com/work-room-umi/ld50-maingame/pull/158
