### ISSUE TITLE
UIのロゴ画像とボタン画像の差し替え

### ISSUE THREAD

**Issue by riyadazo** [work-room-umi/ld50-maingame#155]
# 要件
- ロゴが完成 & ボタンもロゴに合わせてアップデートした
  - fontベタ打ちになっているタイトル部分を、ロゴの画像に差し替える
  - ボタン素材のデータを書き出し直したので差し替える

# 終了条件
- 差し替え用のデータをXDからUnityに変換できている
- unity上でロゴ・ボタンが差し替わっている

**Comment by nim9** [comment]
帰宅したら着手します

**Comment by YoshinoAlice2** [comment]
ロゴの差し替えやっときます

**Comment by YoshinoAlice2** [comment]
XD再コンバートしなくても、ボタン画像だけもらったら差し替えれるんじゃないかな、と思っています
