### ISSUE TITLE
ゲームとしての体裁を整える

### ISSUE THREAD

**Issue by ray45422** [work-room-umi/ld50-maingame#161]
- [x] シーン遷移
  - プレイ画面から結果画面への遷移を作る
    とりあえずHPが0になったら結果画面に飛ばす

- [x] スコアの表示
  - 結果画面にプレイ画面で計算したスコアを表示する

何かあれば追加

**Comment by YoshinoAlice2** [comment]
体裁は整えられた！closeします！
