### ISSUE TITLE
広範囲で衝突判定が出て効果音が発火してしまう

### ISSUE THREAD

**Issue by koiusa** [work-room-umi/ld50-maingame#170]
現在のPlayerShipの衝突判定が大きいため、RigidbodyとColliderがついているオブジェクトで判定すると不必要に音が鳴ってしまう。
判定分けた方がよいでしょうか？
判定を分ける場合既存のコライダとバッティングして自身で発火してしまうため、Tagで切り分けたいです
![スクリーンショット 2022-04-04 184109](https://user-images.githubusercontent.com/71818379/161518596-d1ef4764-a4fb-42f4-b311-0bad83a026ad.png)
。

**Comment by ray45422** [comment]
#181 でやります
