### ISSUE TITLE
PlayerShipLocomoterのエラー

### ISSUE THREAD

**Issue by ray45422** [work-room-umi/ld50-maingame#177]
- プレイ画面以外のPlayerShipLocomoterを全て無効化してください
- SE追加時にでも一緒にお願いします

- [x] タイトル
- [x] リザルト
  - #175
- [x] エンディング？
- [x] クレジット

**Comment by YoshinoAlice2** [comment]
タイトルは修正しました。
リザルトはけしずみさんが直してくれました。
エンディングはクレジット画面に統合され、クレジット画面は船を表示しないのでエラーは出ませんでした。

**Comment by YoshinoAlice2** [comment]
@ray45422

**Comment by ray45422** [comment]
大丈夫でした！ありがとうございます！
