### ISSUE TITLE
音のタイミングが合っていない

### ISSUE THREAD

**Issue by ray45422** [work-room-umi/ld50-maingame#181]
#164 の残タスクです
コライダーの接触判定と実際のダメージ追加処理のタイミングは違うので、攻撃されていないのに音がなる・攻撃されたのに音がならないということが発生すると思います。

Attackにイベントを追加して攻撃時に呼び出されるようにしてもらうのでそこでサウンドを再生するようにお願いできますか。
Attackと同じオブジェクトにコンポーネントを挿してAttackコンポーネントのイベントに音声を再生するイベントを追加するというのが理想形だと思います。SESharkにAtterckコンポーネントを取得する処理を追加して、そのAttackコンポーネントのイベントにPlaySoundを追加してやるといいと思います。

下にタスクとして分割してみたのでわからないことがあれば聞いてください。

- [x] Attackコンポーネントのイベントにデリゲートを追加する
  - #180 でダメージが入った場合に発火するイベントを追加してもらうので、それに音を鳴らすデリゲートを追加してください

- [x] 汎用コンポーネントにする
  - 現時点ではサメ専用コンポーネントのようになっているためAttackコンポーネントが使われているところ全体で使えるようにする
  - 対象
    - [x] サメ
    - [x] ウニ
    - [x] 岩

**Comment by koiusa** [comment]
了解です
PlayerShipの自然破壊時はそのような実装梶田さんに頼んでいれてもらってます
