### ISSUE TITLE
音の発生位置

### ISSUE THREAD

**Issue by ray45422** [work-room-umi/ld50-maingame#192]
音の発生位置が正しくないオブジェクトがある

- [x] プレイヤー
  - PlayerManagerに音源が追加されているがこれはPlayerShipの移動に追従しない
  - PlayerShipに移動する

- [x] 敵
  - [x] サメ
  - [x] ウニ

- [x] 浮遊物
  - これもプレイヤーと同じだと思う
  - メッシュのあるところに音源を配置する
  - #189 も原因？
  - #200
  - [x] 木材

**Comment by YoshinoAlice2** [comment]
全部終わったはずです！
