### ISSUE TITLE
スクリーンスペースで海と重なる領域白いアウトラインが出る。

### ISSUE THREAD

**Issue by HarukaKajita** [work-room-umi/ld50-maingame#195]
![image](https://user-images.githubusercontent.com/26737394/161577739-9b2fd17b-8d11-4bed-9042-71f8b86e3c4e.png)

船も岩もなってる。
シェーダー修正だけで解決できるかは分からないので、その辺の判断も込みで調査してほしい。できそうなら修正してほしい。

**Comment by noriben327** [comment]
現状の調査状況
アンチエイリアスをOnにすると出る。なぜそうなるかはわからんけど。
![image](https://user-images.githubusercontent.com/40428780/161580644-6b29237f-d6a4-4592-86a7-59d27ff1ecf2.png)

**Comment by noriben327** [comment]
解決法
ProjectSettingsで設定できるほうのAAを使わずに、Camera側のAAを使う。

**Comment by YoshinoAlice2** [comment]
解決したのでissueをcloseします！
