### ISSUE TITLE
船体の薄く表示されているコリジョンを非表示にする

### ISSUE THREAD

**Issue by tanitta** [work-room-umi/ld50-maingame#198]

**Comment by tanitta** [comment]
![image](https://user-images.githubusercontent.com/1937287/161591517-048f63e6-d014-49d4-a900-dc3a8050064c.png)

**Comment by YoshinoAlice2** [comment]
修正を確認しました！Closeします！

**Comment by YoshinoAlice2** [comment]
https://github.com/work-room-umi/ld50-maingame/pull/205#issue-1192059703
