### ISSUE TITLE
船との接触以外でなってしまう問題回避

### ISSUE THREAD

**Issue by HarukaKajita** [work-room-umi/ld50-maingame#200]
今って漂流物同士の接触とかでも音がなっていますよね？多分。
SETriggerのOnCollisionEnter/OnTriggerEnterでInvokeするかどうかのバリデーションチェックみたいな処理で回避出来ると思います。
船に当たったかどうかは、OnCollisionEnterなら、collision.gameObject.layer == LayerMask.NameToLayer("ShipCollider")で判断出来ると思います！できなかったら、collision.gameObject.layer == 6 ならできるかも。

もし他の意図してないタイミングで音が出てて困ってたら声かけて下さい！

**Comment by ray45422** [comment]
やってみます

**Comment by ray45422** [comment]
いけました
