### ISSUE TITLE
船の波しぶきのエフェクト

### ISSUE THREAD

**Issue by noriben327** [work-room-umi/ld50-maingame#21]
船が移動したときの波しぶきエフェクト。
パーティクルで作ろうかな。

**Comment by noriben327** [comment]
現状こんな感じ

![image](https://user-images.githubusercontent.com/40428780/161417992-a8efddbc-ec18-4c8c-b053-97806aa9ddd9.png)

**Comment by HarukaKajita** [comment]
他にmustな演出なければもっとモリモリにして欲しい！

**Comment by noriben327** [comment]
もりもりりょかい！
いったん他のエフェクトにとりかかってからにします。

**Comment by noriben327** [comment]
船が止まってるときもエフェクト少し出るようにしてあるけど、ないほうがいいかも？

**Comment by YoshinoAlice2** [comment]
パーティクルは完成しています！
