### ISSUE TITLE
エフェクトをプレハブに組み込む

### ISSUE THREAD

**Issue by HarukaKajita** [work-room-umi/ld50-maingame#215]

**Comment by HarukaKajita** [comment]
- [x] VFXEmitterComponent
- [x] PrefabとDestroyまでの時間をserializeFieldで持つ
- [x] PrefabをInstantiateしてパーティクルを発火。n秒後にDestroyするEmit()関数をpublicで持つ。prefabがnullならreturn。

-----------------------------------------------------------------------------------------------------------------------------

- [x] PlayerShip
- [x] VFXEmitterComponentがついたオブジェクトを子に追加
- [x] ダメージを受けたらVFXEmitterComponentのEmit()関数をコール
- [x] Fixを取得したらFixのEmitVFXをコール

-----------------------------------------------------------------------------------------------------------------------------

- [x] Fix
- [x] VFXEmitterComponentがついたオブジェクトを子に追加
- [x] VFXEmitterComponentのEmitをコールするだけのEmitVFX()関数追加

-----------------------------------------------------------------------------------------------------------------------------

- [x] Attack
- [x] VFXEmitterComponentがついたオブジェクトを子に追加
- [x] VFXEmitterComponentのEmitをコールするだけのEmitVFX()関数追加

-----------------------------------------------------------------------------------------------------------------------------

- [x] PlayerShipLocomoter
- [x] VFXEmitterComponentがついたオブジェクトを子に追加
- [x] スピードによって実行頻度を変えつつ、VFXEmitterComponentのEmitをコールするだけのEmitVFX()関数追加

-----------------------------------------------------------------------------------------------------------------------------

担当したやつのプレハブをテストしつつセットアップしましょう。

**Comment by HarukaKajita** [comment]
サメと岩については申し訳ない

**Comment by koiusa** [comment]
FixのAddDamageにEmit呼ぶ処理ついきしちゃったんですけど、PlayerShipで読んでるから要らんかったんですね、すいません
