### ISSUE TITLE
DrifterManager Componentの実装

### ISSUE THREAD

**Issue by HarukaKajita** [work-room-umi/ld50-maingame#24]
漂流物管理

- スポーン
- デスポーン
- 船に管理を渡す

**Comment by TrsNium** [comment]
![Screenshot 2022-04-02 20-54-43](https://user-images.githubusercontent.com/11388424/161381925-9f9a1b85-48d2-4d17-af66-542b73a79eda.png)

**Comment by TrsNium** [comment]
shipからある程度あるところからspawnさせたけど、これでどうじゃろ

**Comment by TrsNium** [comment]
![Screenshot 2022-04-02 20-56-02](https://user-images.githubusercontent.com/11388424/161381954-2ebd11e8-903a-4601-bed0-52ef75ece3c2.png)

**Comment by TrsNium** [comment]
todo　船にいい感じの情報を渡せるようにする
欲しい情報なんだけけ
kjtさんに後で聞く

**Comment by HarukaKajita** [comment]
- [ ] 船にくっついたらmanagedから外す
- [ ] Drifter ComponentをInstantiateする時に必要な情報(wave)とかを渡して初期化する必要があるっぽい

**Comment by HarukaKajita** [comment]
- DrifterがDrifterManagerから生成された時点で、wave変数がNullになるのでシーンのWavesを渡す
- 船に漂流物がくっついたらDrifterをManagedから外す

 船にくっついたらDrifterManagerの子のオブジェクトが、子から離れて船に持っていかれるのでその辺を利用してManagedから外せそうです。

**Comment by HarukaKajita** [comment]
船側からくっつくときにこのメソッド呼んでほしいとかあればそれでも大丈夫です！

あと、親子関係うまく変えるために_childにも外部からアクセスしたいです！

**Comment by HarukaKajita** [comment]
Managerのshipの型をPlayerShipにしてNullだったらFindObjectOfType<PlayerShip>()で初期化してほしいです！

**Comment by HarukaKajita** [comment]
_shipの型をPlayerShipLocomoterからPlayerShipにしてもらえると助かります！
