### ISSUE TITLE
船のprefabの作成

### ISSUE THREAD

**Issue by tanitta** [work-room-umi/ld50-maingame#3]
# 必要なもの

- [x] 操作制御 #4 
- [x] 仮モデルの作成
- [x] ヨッシャさん作成のモデル一式追加
- [x] 船が動くときの音
- [ ] 水しぶきの追加

**Comment by OtObOx** [comment]
以下の効果音を船のprefabに入れ込んでください
SEイベント名|パラメーター|内容|詳細|
| ------------- | ------------- |------------- |------------- |
ship_speed|ship_speed|水しぶき|
creak|creak_sound|常時なってるクリーク音と0.9以上で強いクリーク音が入る

**Comment by tanitta** [comment]
@HarukaKajita が水しぶきの追加を実装したらclose.
