### ISSUE TITLE
Fix Component

### ISSUE THREAD

**Issue by HarukaKajita** [work-room-umi/ld50-maingame#30]
船についた漂流物

- ダメージ受けたら削除
- 攻撃されたらPlayerShipに報告？

備考
- PlayerShipの管理下にあるはず
- PlayerShipが時間経過のダメージとか消えるパーツの選定をする
- PlayerShipから削除とかの命令がくる？

ダメージ管理の仕様は相談したい

**Comment by tanitta** [comment]
#37 の実装と絡みそうなのでかじたさんにassignしました。
