### ISSUE TITLE
UIワイヤーフレームの作成

### ISSUE THREAD

**Issue by riyadazo** [work-room-umi/ld50-maingame#32]
# 要件
- UIやゲームオブジェクト、エフェクトの配置のサイズ感の決定
  - @YoshinoAlice2 他モデラーとの相談必須（作り込みに影響するため）

# 終了条件
- ワイヤーフレーム作成
- 関係者と合意がとれる

**Comment by riyadazo** [comment]
XDのURL
https://xd.adobe.com/view/b6d334a6-4eba-43fb-b5a5-e06cec97322c-e380/

## Start
![image](https://user-images.githubusercontent.com/101875061/161385809-cfebf442-e02a-425b-95d1-895b57019042.png)
 
## play
![image](https://user-images.githubusercontent.com/101875061/161385823-39c97ea9-04a3-4ae9-9d16-029a75a22adc.png)

## Result
![image](https://user-images.githubusercontent.com/101875061/161386969-ebcb607b-4dce-4575-b9ba-848031bcd813.png)

## END and Credit
![image](https://user-images.githubusercontent.com/101875061/161385852-937400fe-3c61-4c95-8448-93d13c1f4a29.png)

**Comment by riyadazo** [comment]
## 関係者に見てほしい所

- [x] モデルを作るために不足している情報はない
- [x] 実装するために不足している情報はない
- [x] ゲームをプレイするために最低限の情報が揃っている

**Comment by YoshinoAlice2** [comment]
モデルを作るのに不足してる情報は無いです！
最低限必要なもの揃ってそうです！

**Comment by riyadazo** [comment]
### 備考
- 現状Result には timeしかないが、増える可能性もある。確実にあるのはtime。
  - 距離と時間でスコア掛け算の案もあるが、それでゲームが面白くなるかどうかの議論の詰め不足があるので一旦除外

**Comment by tanitta** [comment]
確認しました。良さそうです。
（あとで調整するかもですがResult画面でSinking...と書いているのに船が元気な姿で界面に浮いているのがちょっと気になるかもです。見せ方に工夫がいるかも？）

**Comment by riyadazo** [comment]
>Result画面でSinking...と書いているのに船が元気な姿で界面に浮いているのがちょっと気になるかも

![image](https://user-images.githubusercontent.com/101875061/161386969-ebcb607b-4dce-4575-b9ba-848031bcd813.png)

わかりかつSinkingだと沈没確定エンドになりそうなので素直にResultにしておきます🙏
最終的なプレイヤー個々の船の結果を見せたい画面のはずなので、海の上じゃなくてResult的抽象背景に差し替えときます @tanitta

**Comment by tanitta** [comment]
![image](https://cdn.discordapp.com/attachments/950811374722908220/954423770221781082/LGTM.gif)

**Comment by nim9** [comment]
確認しました。UI実装に不足しているものは無さそうです。

**Comment by riyadazo** [comment]
お三方ありがたや　ほなcloseします🙏
