### ISSUE TITLE
PlayerShip Component

### ISSUE THREAD

**Issue by TrsNium** [work-room-umi/ld50-maingame#37]
- Fix Componentが船体に付着した場合、PlayerShip Prefabにgameobjectがぶら下がる
- 船体のいい感じの場所に漂着物をつける

**Comment by HarukaKajita** [comment]
今のdevのサンプルだと、設置位置が離れすぎているので設置をいい感じに修正します。

**Comment by tanitta** [comment]
基本的な機能は実装できたのでcloseします。
