### ISSUE TITLE
UIのunity向け変換作業

### ISSUE THREAD

**Issue by riyadazo** [work-room-umi/ld50-maingame#38]
# 要件
- 差分込でつくったワイヤーフレームをXDコンポーネント化して、Unity上で表示出来るかのチェック
- 後から正式なUIに差し替えても使えるような作り方
- 実装者に渡してみてUnityじょうで差し替えるだけで使える状態になってると良い

# 終了条件
- 実装者と作業者間で合意取れたら終了

**Comment by riyadazo** [comment]
![image](https://user-images.githubusercontent.com/101875061/161415820-777a0d59-506e-4f89-980b-236f95a270db.png)
とりこめたっぽい
nimさんに触ってもらうようにパス

**Comment by nim9** [comment]
![UIWIP](https://user-images.githubusercontent.com/50519246/161416856-1d291edf-7032-400f-a914-7e62f4bc7b87.gif)
行けそう

**Comment by riyadazo** [comment]
大体取り込めたので終了
