### ISSUE TITLE
ScoreManager

### ISSUE THREAD

**Issue by HarukaKajita** [work-room-umi/ld50-maingame#49]
スコアの計算ロジック

**Comment by tanitta** [comment]
[Unity C# シングルトンパターンの実装 - Qiita](https://qiita.com/calmbooks/items/9cf32c6dd36b724b155e#c%E3%81%A7%E3%81%AE%E3%82%B7%E3%83%B3%E3%82%B0%E3%83%AB%E3%83%88%E3%83%B3%E3%83%91%E3%82%BF%E3%83%BC%E3%83%B3)

これ参考にScoreManagementSceneにScoreManagerを追加してもらえればOKです。

**Comment by tanitta** [comment]
スコアを外から操作できると良さそうです。publicなメソッドとしては
- Add
- Get
- Reset
とかあたりでしょうか。

**Comment by koiusa** [comment]
ResetはUnityで予約イベントメソッドなので別名にした方がいいかもしれません

**Comment by tanitta** [comment]
現在スコアの話の最新が時間のみを考慮して計算を行う方向になっているので、
ScoreManagerで時間を計測する仕組みと計測した時間を返すmethodを実装してください。
時間を計算する仕組みはStartとStopの2つのmethodで操作し、Update等を用いて時間をカウントする形で実装すると良さそうです。

**Comment by koiusa** [comment]
仕様に合わせて修正しました。
認識祖語ありましたらよろしくお願いします。
Startが予約メソッド名なので以下のメソッド名で実装しました。
StartScore、StopScore、ClearScore

**Comment by ray45422** [comment]
MonoBehaviourを継承してコンポーネントとして使うこととシングルトンパターンを両立するのは無理だと思う。
ScoreManagerはスコアを保管することに専念してスコアの加算などは別のところから行うべきではないだろうか。
