### ISSUE TITLE
Attack Componentの実装

### ISSUE THREAD

**Issue by tanitta** [work-room-umi/ld50-maingame#50]
接触したPlayerShip（漂着物？）にダメージを与えるcomponentです。
効果音の再生もここでやってしまって良さそうです。

- 同時にダメージを与えられる漂流物の数
- ダメージ量
を持ってると良いかも

**Comment by HarukaKajita** [comment]
これってinterface Attackableにしたいって話になったんでしたっけ？
個々のオブジェクトのレベル分けで、

- 同時にダメージを与えられる漂流物の数
- ダメージ量

を持たせたら良いかなと思ったんですが、抽象クラスにしてしまって上記の変数も共通して持たせてしまうので良いかなと思ってます。どうですかね。
