### ISSUE TITLE
ゲームタイトルを決める

### ISSUE THREAD

**Issue by tanitta** [work-room-umi/ld50-maingame#56]
案です。他にあったらコメントぶら下げてください
- Cheep Ship
- Theseus

**Comment by riyadazo** [comment]
- Sinking limit
- SIZUMU
- SUSUME

**Comment by riyadazo** [comment]
Ship = 大型の船
Boat = 小型の船

**Comment by noriben327** [comment]
Cheap Boat
Cheap Blue

**Comment by ray45422** [comment]
タイトルは **Cheap Blue** です
