### ISSUE TITLE
Ocean Component

### ISSUE THREAD

**Issue by HarukaKajita** [work-room-umi/ld50-maingame#71]
海の波の制御（演出）
船へダメージを常時与える
他にも演出的なコントロールしてもろても面白そう

備考
波の揺れを頂点シェーダーで処理せずにメッシュの変形をして欲しい。
海面のコライダーがあると漂流物のプカプカが出来るようになるので。

**Comment by TrsNium** [comment]
@HarukaKajita 
イメージこんな感じで会ってます？
ref.
https://youtu.be/ve317KRKVoQ
https://youtu.be/_Ij24zRI9J0

**Comment by TrsNium** [comment]
@HarukaKajita 
自分のほうでとりあえずやってみるので、朝までにできてなかったらシバイテください
