### ISSUE TITLE
船体に漂着物が接触した場合の処理

### ISSUE THREAD

**Issue by ray45422** [work-room-umi/ld50-maingame#75]
私が認識している範囲の仕様を書いておきます。適当に書き換えてください。

- [ ]  船の適切な場所に漂着物を設置する #30
  - ~他の設置済みの漂着物と干渉しない位置？~
  - 均等に設置されるようにする？
  - 設置時にFMODのイベントが発火するように設定する

- [ ] 設置時のエフェクト #139

- [x] 設置時に音が鳴るようにする
  - 設置音の作成
  - 設置時に発火するイベントの設定

**Comment by HarukaKajita** [comment]
@OtObOx 
設置処理は、「船の周囲から船に向かって、漂着物サイズ程度の球体をぶつけてぶつかった所に漂着物を固定。」という感じの処理なので多少干渉するし、隙間も空きうる。
設置時のイベント発火、日曜日に追加します。ついでにサウンドを鳴らしたいイベントを設置以外の所含めてリストアップしてissueにまとめてもらえると助かります！

**Comment by OtObOx** [comment]
以下の効果音を漂流物が船に接触した際再生してください。
宜しくお願い致します。
SEイベント名|パラメーター|内容|詳細|
| ------------- | ------------- |------------- |------------- |
|Stick||漂着物取得音|引っ付く感じ
