### ISSUE TITLE
UIに関わる必要effectの洗い出し

### ISSUE THREAD

**Issue by riyadazo** [work-room-umi/ld50-maingame#8]
# 要件
- #2 確定後(あるいは)、UIパーツのプロトタイプができた段階で @noriben327 とeffectの必要可否と洗い出しを行う

# 終了条件
- 各UIパーツ毎に要件にeffect差分が追記・issues化される
- あるいは必要ないことがわかる

**Comment by riyadazo** [comment]
@noriben327 とちょろっと話してそんなに必要な箇所がなさそうだったのでcloseする

**Comment by noriben327** [comment]
りょかい！
