### ISSUE TITLE
ProjectSettingsのDepth TextureとOpaque Textureのチェックボックスをオンにする

### ISSUE THREAD

**Issue by noriben327** [work-room-umi/ld50-maingame#81]
海シェーダーでDepthやSceneColorを使いたいので。

**Comment by noriben327** [comment]
![image](https://user-images.githubusercontent.com/40428780/161406202-7473745e-5877-4d5a-9216-a9f45d52d1d9.png)

**Comment by tanitta** [comment]
![image](https://cdn.discordapp.com/attachments/950811374722908220/954423770221781082/LGTM.gif)
